# Generated by Django 5.1.2 on 2024-10-20 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Control',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_order_limit', models.IntegerField(default=0)),
                ('max_loss_limit', models.FloatField(default=0.0)),
                ('max_profit_limit', models.FloatField(default=0.0)),
                ('max_profit_mode', models.BooleanField(default=False)),
                ('max_order_count_mode', models.BooleanField(default=False)),
                ('is_killed_once', models.BooleanField(default=False)),
            ],
        ),
    ]
