# Generated by Django 5.1.2 on 2024-10-20 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_control_is_killed_once_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='control',
            name='max_loss_mode',
            field=models.CharField(choices=[('0', 'Disable'), ('1', 'Enable')], default='0', max_length=1),
        ),
    ]
