# Generated by Django 5.1.2 on 2024-10-22 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_control_max_loss_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dhan_access_token',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
