# Generated by Django 5.1.2 on 2024-10-23 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_dhankillprocesslog'),
    ]

    operations = [
        migrations.AddField(
            model_name='control',
            name='max_order_limit_level_2',
            field=models.IntegerField(default=0),
        ),
    ]
