# Generated by Django 5.1.2 on 2024-10-23 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_control_max_order_limit_level_2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='control',
            old_name='max_order_limit_level_2',
            new_name='peak_order_limit',
        ),
    ]
