# Generated by Django 5.1.2 on 2024-10-23 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_rename_max_order_limit_level_2_control_peak_order_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_killed_once',
            field=models.BooleanField(default=False),
        ),
    ]
