# Generated by Django 5.1.2 on 2024-10-23 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_user_is_killed_once'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_killed_once',
            new_name='kill_switch_1',
        ),
    ]
