# Generated by Django 5.1.2 on 2024-10-23 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_rename_is_killed_once_user_kill_switch_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='kill_switch_2',
            field=models.BooleanField(default=False),
        ),
    ]
