# Generated by Django 5.1.2 on 2024-10-24 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_user_kill_switch_2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='control',
            old_name='is_killed_once',
            new_name='stoploss_percentage',
        ),
    ]
