# Generated by Django 5.1.2 on 2024-10-28 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_remove_dailyaccountoverview_deposit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyaccountoverview',
            name='actual_profit',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
