# Generated by Django 5.1.2 on 2024-11-01 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_dailyaccountoverview_actual_profit'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='quick_exit',
            field=models.BooleanField(default=False),
        ),
    ]
