# Generated by Django 5.1.2 on 2024-11-05 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0024_control_max_lot_size_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='control',
            name='max_lot_size_limit',
            field=models.FloatField(default=0.0),
        ),
    ]
