# Generated by Django 5.1.2 on 2024-11-07 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0026_control_peak_loss_limit_control_peak_profit_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyaccountoverview',
            name='day_closing',
            field=models.BooleanField(default=False),
        ),
    ]
