# Generated by Django 5.1.2 on 2024-11-07 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0027_dailyaccountoverview_day_closing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailyaccountoverview',
            old_name='day_closing',
            new_name='day_close',
        ),
        migrations.AddField(
            model_name='dailyaccountoverview',
            name='day_open',
            field=models.BooleanField(default=False),
        ),
    ]
