# Generated by Django 5.1.2 on 2024-11-12 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0030_rename_stoploss_percentage_control_stoploss_parameter'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_order_count',
            field=models.IntegerField(default=0),
        ),
    ]
