# Generated by Django 5.1.2 on 2024-11-22 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0034_alter_dailyselfanalysis_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyselfanalysis',
            name='overall_advice',
            field=models.CharField(blank=True, help_text='Profit and Loss Status of the day', max_length=5000, null=True),
        ),
    ]
