# Generated by Django 5.1.2 on 2024-11-25 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0037_userrtcusage'),
    ]

    operations = [
        migrations.AddField(
            model_name='control',
            name='default_peak_order_limit',
            field=models.IntegerField(default=0),
        ),
    ]
