# Generated by Django 5.1.2 on 2024-12-01 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0039_tradingplan_weeklygoalreport_dailygoalreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradingplan',
            name='expected_growth',
            field=models.DecimalField(decimal_places=2, help_text='Expected growth as a percentage (e.g., 15.5 for 15.5%)', max_digits=20),
        ),
    ]
