# Generated by Django 5.1.2 on 2024-12-01 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0040_alter_tradingplan_expected_growth'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingplan',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
