# Generated by Django 5.1.2 on 2024-12-01 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0041_tradingplan_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailygoalreport',
            name='plan_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tradingplan',
            name='plan_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
