# Generated by Django 5.1.2 on 2024-12-01 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0043_alter_tradingplan_plan_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradingplan',
            name='plan_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
