# Generated by Django 5.1.2 on 2024-12-01 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0044_alter_tradingplan_plan_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailygoalreport',
            name='plan_name',
        ),
        migrations.RemoveField(
            model_name='weeklygoalreport',
            name='plan_name',
        ),
        migrations.AddField(
            model_name='dailygoalreport',
            name='plan_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weeklygoalreport',
            name='plan_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
