# Generated by Django 5.1.2 on 2024-12-01 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0045_remove_dailygoalreport_plan_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailygoalreport',
            name='plan_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weeklygoalreport',
            name='plan_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
