# Generated by Django 5.1.2 on 2025-01-17 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0047_alter_control_max_order_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auth_code',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
